# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ðŸ¤–CI run Regression in QAðŸ§ª
run-name: ${{github.actor}}ðŸ‘¨ðŸ»â€ðŸ”¬ run Regression in ${{github.ref_name}}

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: ðŸ’»Checkout
              uses: actions/checkout@v3

            - name: ðŸ’¿Set up JAVA 20 with Maven
              uses: actions/setup-java@v3
              with:
                  java-version: '20'
                  distribution: 'temurin'
                  cache: maven

            - name: Setup ChromeDriver
              uses: nanasess/setup-chromedriver@v2
              with:
              chromedriver-version: '88.0.4324.96'
            - run: |
                  export DISPLAY=:99
                  chromedriver --url-base=/wd/hub &
                  sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

            - name: Run Chrome Headless
              run: |
                  google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 &

            - name: ðŸ§¬Install All Dependencies with Maven
              run: mvn -B package --file pom.xml

            - name: ðŸ§ªRun Selenium tests
              run: mvn -B -X -Dtest=GX_28431_buttonsTest -Dheadless=true test

            # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
            - name: Update dependency graph
              uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
