# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: ğŸ¤–CI run Regression in QAğŸ§ª
run-name: ${{github.actor}}ğŸ‘¨ğŸ»â€ğŸ”¬ run Regression in ${{github.ref_name}}

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: ğŸ’»Checkout
              uses: actions/checkout@v3

            - name: ğŸ’¿Set up JAVA 20 with Maven
              uses: actions/setup-java@v3
              with:
                  java-version: '20'
                  distribution: 'temurin'
                  cache: maven

            - name: Setup ChromeDriver
              uses: nanasess/setup-chromedriver@v2
              with:
                  chromedriver-version: '88.0.4324.96'

            - name: Setup Xvfb (Optional)
              run: |
                  export DISPLAY=:99
                  chromedriver --url-base=/wd/hub &
                  sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

            - name: ğŸ§¬Install All Dependencies with Maven
              run: mvn -B package --file pom.xml

            - name: ğŸ§ªRun Selenium tests
              run: mvn -B -X -Dtest=GX_28431_buttonsTest -Dheadless=true test
